# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # environment: env1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello, world! $RANDOM" >> output.txt

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $TOKEN | rev
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: output.txt
